<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Campus extends \Entity\Campus implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function get_cursos()
    {
        $this->__load();
        return parent::get_cursos();
    }

    public function set_cursos($cursos)
    {
        $this->__load();
        return parent::set_cursos($cursos);
    }

    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function setCidade($cidade)
    {
        $this->__load();
        return parent::setCidade($cidade);
    }

    public function getCidade()
    {
        $this->__load();
        return parent::getCidade();
    }

    public function getIdCampus()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idCampus"];
        }
        $this->__load();
        return parent::getIdCampus();
    }

    public function setInstituicao(\Entity\Instituicao $instituicao = NULL)
    {
        $this->__load();
        return parent::setInstituicao($instituicao);
    }

    public function getInstituicao()
    {
        $this->__load();
        return parent::getInstituicao();
    }

    public function addOrientador(\Entity\Orientador $orientador)
    {
        $this->__load();
        return parent::addOrientador($orientador);
    }

    public function removeOrientador(\Entity\Orientador $orientador)
    {
        $this->__load();
        return parent::removeOrientador($orientador);
    }

    public function getOrientador()
    {
        $this->__load();
        return parent::getOrientador();
    }

    public function addInstituicao(\Entity\Instituicao $instituicao)
    {
        $this->__load();
        return parent::addInstituicao($instituicao);
    }

    public function getOrientadores()
    {
        $this->__load();
        return parent::getOrientadores();
    }

    public function setOrientadores($orientadores)
    {
        $this->__load();
        return parent::setOrientadores($orientadores);
    }

    public function jsonSerialize()
    {
        $this->__load();
        return parent::jsonSerialize();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'nome', 'cidade', 'idCampus', 'instituicao', 'cursos');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}