<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TrabalhoOrientadorCampus extends \Entity\TrabalhoOrientadorCampus implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setEmailTrabalho($emailTrabalho)
    {
        $this->__load();
        return parent::setEmailTrabalho($emailTrabalho);
    }

    public function getEmailTrabalho()
    {
        $this->__load();
        return parent::getEmailTrabalho();
    }

    public function getSequencia()
    {
        $this->__load();
        return parent::getSequencia();
    }

    public function setSequencia($sequencia)
    {
        $this->__load();
        return parent::setSequencia($sequencia);
    }

    public function getTrabalho()
    {
        $this->__load();
        return parent::getTrabalho();
    }

    public function setTrabalho($trabalho)
    {
        $this->__load();
        return parent::setTrabalho($trabalho);
    }

    public function getOrientador()
    {
        $this->__load();
        return parent::getOrientador();
    }

    public function setOrientador($orientador)
    {
        $this->__load();
        return parent::setOrientador($orientador);
    }

    public function getCampus()
    {
        $this->__load();
        return parent::getCampus();
    }

    public function setCampus($campus)
    {
        $this->__load();
        return parent::setCampus($campus);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'sequencia', 'emailTrabalho', 'trabalho', 'orientador', 'campus');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}