<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TrabalhoAutorCurso extends \Entity\TrabalhoAutorCurso implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getTrabalho()
    {
        $this->__load();
        return parent::getTrabalho();
    }

    public function setTrabalho($trabalho)
    {
        $this->__load();
        return parent::setTrabalho($trabalho);
    }

    public function getAutor()
    {
        $this->__load();
        return parent::getAutor();
    }

    public function setAutor($autor)
    {
        $this->__load();
        return parent::setAutor($autor);
    }

    public function getCurso()
    {
        $this->__load();
        return parent::getCurso();
    }

    public function setCurso($curso)
    {
        $this->__load();
        return parent::setCurso($curso);
    }

    public function getSequencia()
    {
        $this->__load();
        return parent::getSequencia();
    }

    public function setSequencia($sequencia)
    {
        $this->__load();
        return parent::setSequencia($sequencia);
    }

    public function getEmailTrabalho()
    {
        $this->__load();
        return parent::getEmailTrabalho();
    }

    public function setEmailTrabalho($email_trabalho)
    {
        $this->__load();
        return parent::setEmailTrabalho($email_trabalho);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'sequencia', 'email_trabalho', 'trabalho', 'autor', 'curso');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}