<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Voluntario extends \Entity\Voluntario implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setObservacoes($observacoes)
    {
        $this->__load();
        return parent::setObservacoes($observacoes);
    }

    public function getObservacoes()
    {
        $this->__load();
        return parent::getObservacoes();
    }

    public function setManha($manha)
    {
        $this->__load();
        return parent::setManha($manha);
    }

    public function getManha()
    {
        $this->__load();
        return parent::getManha();
    }

    public function setTarde($tarde)
    {
        $this->__load();
        return parent::setTarde($tarde);
    }

    public function getTarde()
    {
        $this->__load();
        return parent::getTarde();
    }

    public function setNoite($noite)
    {
        $this->__load();
        return parent::setNoite($noite);
    }

    public function getNoite()
    {
        $this->__load();
        return parent::getNoite();
    }

    public function setTelefone1($telefone1)
    {
        $this->__load();
        return parent::setTelefone1($telefone1);
    }

    public function getTelefone1()
    {
        $this->__load();
        return parent::getTelefone1();
    }

    public function setTelefone2($telefone2)
    {
        $this->__load();
        return parent::setTelefone2($telefone2);
    }

    public function getTelefone2()
    {
        $this->__load();
        return parent::getTelefone2();
    }

    public function setTelefone3($telefone3)
    {
        $this->__load();
        return parent::setTelefone3($telefone3);
    }

    public function getTelefone3()
    {
        $this->__load();
        return parent::getTelefone3();
    }

    public function setPresenca($presenca)
    {
        $this->__load();
        return parent::setPresenca($presenca);
    }

    public function getPresenca()
    {
        $this->__load();
        return parent::getPresenca();
    }

    public function getCurso()
    {
        $this->__load();
        return parent::getCurso();
    }

    public function setCurso(\Entity\Curso $curso)
    {
        $this->__load();
        return parent::setCurso($curso);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function setUsuario(\Entity\Usuario $usuario)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function jsonSerialize()
    {
        $this->__load();
        return parent::jsonSerialize();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'status', 'observacoes', 'manha', 'tarde', 'noite', 'telefone1', 'telefone2', 'telefone3', 'presenca', 'usuario', 'curso');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}