<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Sessao extends \Entity\Sessao implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setNumero($numero)
    {
        $this->__load();
        return parent::setNumero($numero);
    }

    public function getNumero()
    {
        $this->__load();
        return parent::getNumero();
    }

    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function setSala($sala)
    {
        $this->__load();
        return parent::setSala($sala);
    }

    public function getSala()
    {
        $this->__load();
        return parent::getSala();
    }

    public function setNomeSala($nomeSala)
    {
        $this->__load();
        return parent::setNomeSala($nomeSala);
    }

    public function getNomeSala()
    {
        $this->__load();
        return parent::getNomeSala();
    }

    public function setAndar($andar)
    {
        $this->__load();
        return parent::setAndar($andar);
    }

    public function getAndar()
    {
        $this->__load();
        return parent::getAndar();
    }

    public function setNomeAndar($nomeAndar)
    {
        $this->__load();
        return parent::setNomeAndar($nomeAndar);
    }

    public function getNomeAndar()
    {
        $this->__load();
        return parent::getNomeAndar();
    }

    public function setData($data)
    {
        $this->__load();
        return parent::setData($data);
    }

    public function getData()
    {
        $this->__load();
        return parent::getData();
    }

    public function setHoraIni($horaIni)
    {
        $this->__load();
        return parent::setHoraIni($horaIni);
    }

    public function getHoraIni()
    {
        $this->__load();
        return parent::getHoraIni();
    }

    public function setHoraFim($horaFim)
    {
        $this->__load();
        return parent::setHoraFim($horaFim);
    }

    public function getHoraFim()
    {
        $this->__load();
        return parent::getHoraFim();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getIdSessao()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idSessao"];
        }
        $this->__load();
        return parent::getIdSessao();
    }

    public function setModalidade(\Entity\Modalidade $fkModalidade = NULL)
    {
        $this->__load();
        return parent::setModalidade($fkModalidade);
    }

    public function getModalidade()
    {
        $this->__load();
        return parent::getModalidade();
    }

    public function addAvaliador(\Entity\Avaliador $fkAvaliador)
    {
        $this->__load();
        return parent::addAvaliador($fkAvaliador);
    }

    public function removeAvaliador(\Entity\Avaliador $fkAvaliador)
    {
        $this->__load();
        return parent::removeAvaliador($fkAvaliador);
    }

    public function getAvaliador()
    {
        $this->__load();
        return parent::getAvaliador();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'numero', 'nome', 'sala', 'nomeSala', 'andar', 'nomeAndar', 'data', 'horaIni', 'horaFim', 'status', 'idSessao', 'modalidade');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}