<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Trabalho extends \Entity\Trabalho implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setNivel($nivel)
    {
        $this->__load();
        return parent::setNivel($nivel);
    }

    public function getNivel()
    {
        $this->__load();
        return parent::getNivel();
    }

    public function setTitulo($titulo)
    {
        $this->__load();
        return parent::setTitulo($titulo);
    }

    public function getTitulo()
    {
        $this->__load();
        return parent::getTitulo();
    }

    public function setTituloOrdenar($tituloOrdenar)
    {
        $this->__load();
        return parent::setTituloOrdenar($tituloOrdenar);
    }

    public function getTituloOrdenar()
    {
        $this->__load();
        return parent::getTituloOrdenar();
    }

    public function setPalavra1($palavra1)
    {
        $this->__load();
        return parent::setPalavra1($palavra1);
    }

    public function getPalavra1()
    {
        $this->__load();
        return parent::getPalavra1();
    }

    public function setPalavra2($palavra2)
    {
        $this->__load();
        return parent::setPalavra2($palavra2);
    }

    public function getPalavra2()
    {
        $this->__load();
        return parent::getPalavra2();
    }

    public function setPalavra3($palavra3)
    {
        $this->__load();
        return parent::setPalavra3($palavra3);
    }

    public function getPalavra3()
    {
        $this->__load();
        return parent::getPalavra3();
    }

    public function setApoiadores($apoiadores)
    {
        $this->__load();
        return parent::setApoiadores($apoiadores);
    }

    public function getApoiadores()
    {
        $this->__load();
        return parent::getApoiadores();
    }

    public function setResumo($resumo)
    {
        $this->__load();
        return parent::setResumo($resumo);
    }

    public function getResumo()
    {
        $this->__load();
        return parent::getResumo();
    }

    public function setResumo2($resumo2)
    {
        $this->__load();
        return parent::setResumo2($resumo2);
    }

    public function getResumo2()
    {
        $this->__load();
        return parent::getResumo2();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setDataCadastro($dataCadastro)
    {
        $this->__load();
        return parent::setDataCadastro($dataCadastro);
    }

    public function getDataCadastro()
    {
        $this->__load();
        return parent::getDataCadastro();
    }

    public function setDataAtualizacao($dataAtualizacao)
    {
        $this->__load();
        return parent::setDataAtualizacao($dataAtualizacao);
    }

    public function getDataAtualizacao()
    {
        $this->__load();
        return parent::getDataAtualizacao();
    }

    public function setIpCadastro($ipCadastro)
    {
        $this->__load();
        return parent::setIpCadastro($ipCadastro);
    }

    public function getIpCadastro()
    {
        $this->__load();
        return parent::getIpCadastro();
    }

    public function setIpAtualizacao($ipAtualizacao)
    {
        $this->__load();
        return parent::setIpAtualizacao($ipAtualizacao);
    }

    public function getIpAtualizacao()
    {
        $this->__load();
        return parent::getIpAtualizacao();
    }

    public function setSeqSessao($seqSessao)
    {
        $this->__load();
        return parent::setSeqSessao($seqSessao);
    }

    public function getSeqSessao()
    {
        $this->__load();
        return parent::getSeqSessao();
    }

    public function setNota($nota)
    {
        $this->__load();
        return parent::setNota($nota);
    }

    public function getNota()
    {
        $this->__load();
        return parent::getNota();
    }

    public function setPremiado($premiado)
    {
        $this->__load();
        return parent::setPremiado($premiado);
    }

    public function getPremiado()
    {
        $this->__load();
        return parent::getPremiado();
    }

    public function setArea($area)
    {
        $this->__load();
        return parent::setArea($area);
    }

    public function getArea()
    {
        $this->__load();
        return parent::getArea();
    }

    public function getIdTrabalho()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idTrabalho"];
        }
        $this->__load();
        return parent::getIdTrabalho();
    }

    public function setFkSessao(\Entity\Sessao $sessao = NULL)
    {
        $this->__load();
        return parent::setFkSessao($sessao);
    }

    public function getFkSessao()
    {
        $this->__load();
        return parent::getFkSessao();
    }

    public function setFkModalidade(\Entity\Modalidade $modalidade = NULL)
    {
        $this->__load();
        return parent::setFkModalidade($modalidade);
    }

    public function getFkModalidade()
    {
        $this->__load();
        return parent::getFkModalidade();
    }

    public function setCategoria(\Entity\Categoria $categoria = NULL)
    {
        $this->__load();
        return parent::setCategoria($categoria);
    }

    public function getCategoria()
    {
        $this->__load();
        return parent::getCategoria();
    }

    public function getTurno1()
    {
        $this->__load();
        return parent::getTurno1();
    }

    public function setTurno1($turno1)
    {
        $this->__load();
        return parent::setTurno1($turno1);
    }

    public function getTurno2()
    {
        $this->__load();
        return parent::getTurno2();
    }

    public function setTurno2($turno2)
    {
        $this->__load();
        return parent::setTurno2($turno2);
    }

    public function getTurno3()
    {
        $this->__load();
        return parent::getTurno3();
    }

    public function setTurno3($turno3)
    {
        $this->__load();
        return parent::setTurno3($turno3);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'nivel', 'titulo', 'tituloOrdenar', 'palavra1', 'palavra2', 'palavra3', 'apoiadores', 'resumo', 'resumo2', 'status', 'dataCadastro', 'dataAtualizacao', 'ipCadastro', 'ipAtualizacao', 'seqSessao', 'nota', 'premiado', 'idTrabalho', 'turno1', 'turno2', 'turno3', 'area', 'sessao', 'modalidade', 'categoria');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}