<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Ouvinte extends \Entity\Ouvinte implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setTipoOuvinte($tipoOuvinte)
    {
        $this->__load();
        return parent::setTipoOuvinte($tipoOuvinte);
    }

    public function getTipoOuvinte()
    {
        $this->__load();
        return parent::getTipoOuvinte();
    }

    public function setOutro($outro)
    {
        $this->__load();
        return parent::setOutro($outro);
    }

    public function getOutro()
    {
        $this->__load();
        return parent::getOutro();
    }

    public function setEmpresa($empresa)
    {
        $this->__load();
        return parent::setEmpresa($empresa);
    }

    public function getEmpresa()
    {
        $this->__load();
        return parent::getEmpresa();
    }

    public function setUsuario(\Entity\Usuario $usuario)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function setInstituicao(\Entity\Instituicao $instituicao = NULL)
    {
        $this->__load();
        return parent::setInstituicao($instituicao);
    }

    public function getInstituicao()
    {
        $this->__load();
        return parent::getInstituicao();
    }

    public function setCurso(\Entity\Curso $curso = NULL)
    {
        $this->__load();
        return parent::setCurso($curso);
    }

    public function getCurso()
    {
        $this->__load();
        return parent::getCurso();
    }

    public function setCampus(\Entity\Campus $campus = NULL)
    {
        $this->__load();
        return parent::setCampus($campus);
    }

    public function getCampus()
    {
        $this->__load();
        return parent::getCampus();
    }

    public function jsonSerialize()
    {
        $this->__load();
        return parent::jsonSerialize();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'tipoOuvinte', 'outro', 'empresa', 'usuario', 'instituicao', 'campus', 'curso');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}